<?php
/**
 * @var Mage_Payment_Block_Form $this
 * @var $publicKey string
 * @var $amount string decimal
 * @var $simulatorType int
 */
?>
<style>
    #logo {height:25px; margin-right: 10px;}
    #dd_method_pagantis fieldset.form-list {
        padding-left: 0px;
    }
</style>
<fieldset class="form-list">
    <?php if($simulatorIsEnabled && $pagantisIsEnabled && $publicKey!='') { ?>
        <div class="PagantisSimulator"></div>
        <script type="text/javascript">

            function getPositionSelector() {
                var positionSelector = '<?php echo $pagantisCSSSelector;?>';

                if (positionSelector === 'default') {
                    positionSelector = '.PagantisSimulator';
                }

                return positionSelector;
            }

            function loadSimulator()
            {
                var sdk = pgSDK;

                if ('<?php echo $locale;?>' == 'ES' || '<?php echo $locale;?>' == '') {
                    sdk = pmtSDK;
                }

                var positionSelector = getPositionSelector();
                var pgDiv = document.querySelectorAll(positionSelector);
                if(typeof pgDiv!='undefined' && typeof pgDiv[0]!='undefined' && typeof window.MGSimulatorId!='undefined') {
                    var pgElement = pgDiv[0];
                    if (pgElement.innerHTML != '')
                    {
                        clearInterval(window.MGSimulatorId);
                        return true;
                    }
                }

                if (sdk != 'undefined') {
                    window.MGSimulatorId = sdk.simulator.init({
                        numInstalments : '<?php echo $pagantisQuotesStart;?>',
                        type : <?php echo $pagantisSimulatorType;?>,
                        skin : <?php echo $pagantisSimulatorSkin;?>,
                        locale: '<?php echo strtolower($locale);?>',
                        country: '<?php echo strtolower($country);?>',
                        position : <?php echo $pagantisSimulatorPosition;?>,
                        publicKey: '<?php echo $publicKey; ?>',
                        selector: positionSelector,
                        totalAmount: <?php echo $amount; ?>,
                        totalPromotedAmount:  <?php echo $promotedAmount; ?>,
                        amountParserConfig :  {
                            thousandSeparator: '<?php echo $thousandSeparator;?>',
                            decimalSeparator: '<?php echo $decimalSeparator;?>'
                        }
                    });
                    return false;
                }
                return true;
            }
            if (!loadSimulator()) {
                window.loadingSimulator = setInterval(function () {
                    loadSimulator();
                }, 2000);
            }

        </script>
    <?php } ?>
</fieldset>