<?php
/**
 * @var Mage_Payment_Block_Form $this
 * @var $publicKey string
 * @var $amount string decimal
 * @var $simulatorType int
 */

$_code = $this->getMethodCode();
?>
<style>
    #logo {height:25px; margin-right: 10px;}
</style>
<fieldset class="form-list">
    <?php if($simulatorIsEnabled && $pagantisIsEnabled && $publicKey!='') { ?>
        <div class="PmtSimulator"></div>
        <script type="text/javascript">
            document.querySelectorAll('[value="paylater"]','[type="radio"]')[0].addEventListener('click', function() { pmtClient.simulator.reload(); });

            function loadSimulator()
            {
                var sdk = pgSDK;

                if ('<?=$locale;?>' == 'ES' || '<?=$locale;?>' == '') {
                    var sdk = pmtSDK;
                }

                var pgDiv = document.getElementsByClassName("PagantisSimulator");
                if(typeof pgDiv != 'undefined') {
                    var pmtElement = pgDiv[0];
                    if (pmtElement.innerHTML != '')
                    {
                        clearInterval(window.MGSimulatorId);
                        return true;
                    }
                }

                if (typeof sdk != 'undefined') {
                    sdk.simulator.init({
                        publicKey: '<?php echo $publicKey; ?>',
                        selector: '.PmtSimulator',
                        totalAmount: <?php echo $amount; ?>,
                    });
                    return false;
                }
            }
            window.MGSimulatorId = setInterval(function () {
                loadSimulator();
            }, 2000);

        </script>
    <?php } ?>
</fieldset>