version: "2"

services:
  magento19:
    build:
      dockerfile: Dockerfile-Dev
      context: ./
    depends_on:
      - db
    environment:
      - MAGENTO_LOCALE=es_ES
      - MAGENTO_TIMEZONE=Europe/Madrid
      - MAGENTO_DEFAULT_CURRENCY=EUR
      - MAGENTO_ADMIN_FIRSTNAME=Owner
      - MAGENTO_ADMIN_LASTNAME=Store
      - MAGENTO_ADMIN_EMAIL=admin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=password123
      - MAGENTO_DB_HOST=db
      - MAGENTO_DB_PASSWORD=password
      - MAGENTO_URL=magento19.docker:8080
    volumes:
      - ./extension:/pmt
    networks:
      - internal
      - public
    ports:
      - "8080:80"

  magento-test:
    build:
      dockerfile: Dockerfile-Test
      context: ./
    depends_on:
      - db-test
    environment:
      - MAGENTO_LOCALE=es_ES
      - MAGENTO_TIMEZONE=Europe/Madrid
      - MAGENTO_DEFAULT_CURRENCY=EUR
      - MAGENTO_ADMIN_FIRSTNAME=Owner
      - MAGENTO_ADMIN_LASTNAME=Store
      - MAGENTO_ADMIN_EMAIL=admin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=password123
      - MAGENTO_DB_HOST=db-test
      - MAGENTO_DB_PASSWORD=password
      - MAGENTO_URL=magento-test
    volumes:
      - ./extension:/pmt
    networks:
      - internal
      - public
    ports:
      - "8082:80"

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=magento
    networks:
      - internal

  db-test:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=magento
    networks:
      - internal

  selenium:
    image: selenium/standalone-chrome
    #volumes:
    #  - .dev/shm:/dev/shm
    networks:
      - public
    ports:
      - "4444:4444"

networks:
  internal:
  public:
