version: "3.5"

services:
  magento19-dev:
    container_name: magento19-dev
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MAGENTO_ADMIN_FIRSTNAME=Owner
      - MAGENTO_ADMIN_LASTNAME=Store
      - MAGENTO_ADMIN_EMAIL=admin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=password123
      - MYSQL_HOST=magento19-db-dev
      - MYSQL_DATABASE=magento
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MAGENTO_LOCALE=es_ES
      - MAGENTO_TIMEZONE=Europe/Madrid
      - MAGENTO_DEFAULT_CURRENCY=EUR
      - MAGENTO_URL=magento19-dev.docker:8080
    volumes:
      - ./extension:/pagantis
    links:
      - magento19-db-dev
    ports:
      - "8080:80"
    extra_hosts:
      - "magento19-dev.docker:127.0.0.1"

  magento19-test:
    container_name: magento19-test
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MAGENTO_ADMIN_FIRSTNAME=Owner
      - MAGENTO_ADMIN_LASTNAME=Store
      - MAGENTO_ADMIN_EMAIL=admin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=password123
      - MYSQL_HOST=magento19-db-test
      - MYSQL_DATABASE=magento
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MAGENTO_LOCALE=es_ES
      - MAGENTO_TIMEZONE=Europe/Madrid
      - MAGENTO_DEFAULT_CURRENCY=EUR
      - MAGENTO_URL=magento19-test.docker:8082
    links:
      - magento19-db-test
    ports:
      - "8082:80"
    extra_hosts:
      - "magento19-test.docker:127.0.0.1"

  magento19-db-dev:
    container_name: magento19-db-dev
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=magento

  magento19-db-test:
    container_name: magento19-db-test
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=magento

  selenium:
    image: selenium/standalone-chrome:3.7.1
    ports:
      - "4444:4444"
    extra_hosts:
      - "magento19-test.docker:${DOCKERHOST}"
      - "magento19-dev.docker:${DOCKERHOST}"
