<?php
/**
 * @var int $simulatorType
 * @var bool $enabled
 * @var string $publicKey
 */
if ($pagantisIsEnabled && $pagantisSimulatorIsEnabled && $pagantisPublicKey != '') {
    if ($promoted) {
        echo "<style>
        .pagantis-promotion {
            font-size: 11px;
            display: inline-block;
            width: 100%;
            text-align: center;
            color: #828282;
        }
        .pagantis-promotion .pmt-no-interest{
            color: #00c1d5
        }
    </style>";
        echo "<div class='pagantis-promotion'>$pagantisPromotedMessage</div>";
    }
    ?>
    <script>
        function findPriceSelector()
        {
            var priceDOM = document.querySelector('[id^="product-price"]');
            if (priceDOM != null ) {
                return '[id^="product-price"]';
            }
            priceDOM = document.querySelector('div.add-to-box > div.price-info > div.price-box > p.special-price');
            if (priceDOM != null ) {
                return 'div.add-to-box > div.price-info > div.price-box > p.special-price';
            }

            // Keep default for checkout price.
            return 'default';
        }

        function findQuantitySelector()
        {
            var quantityDOM = document.querySelector('.qty-wrapper #qty');
            if (quantityDOM != null) {
                return '.qty-wrapper #qty';
            }

            return 'default';
        }

        function getPositionSelector() {
            var positionSelector = '<?php echo $pagantisCSSSelector;?>';

            if (positionSelector === 'default') {
                positionSelector = '.PagantisSimulator';
            }

            return positionSelector;
        }

        function loadSimulator()
        {
            var sdk = pgSDK;
            if ('<?php echo $locale;?>' == 'ES') {
                sdk = pmtSDK;
            }

            var positionSelector = getPositionSelector();
            var pgDiv = document.querySelectorAll(positionSelector);

            if(typeof pgDiv!='undefined' && typeof pgDiv[0] != 'undefined' && typeof window.MGSimulatorId!='undefined'){
                var pmtElement = pgDiv[0];
                if (pmtElement.innerHTML != '')
                {
                    clearInterval(window.loading);
                    return true;
                }
            }

            if (sdk != 'undefined') {
                var price = null;
                var quantity = null;
                var positionSelector = getPositionSelector();
                var priceSelector = '<?php echo $pagantisPriceSelector;?>';
                var quantitySelector = '<?php echo $pagantisQuantitySelector;?>';

                if (priceSelector === 'default') {
                    priceSelector = findPriceSelector();
                    if (priceSelector === 'default') {
                        price = '<?php echo $amount;?>';
                    }
                }

                if (quantitySelector === 'default') {
                    quantitySelector = findQuantitySelector();
                    if (quantitySelector === 'default') {
                        quantity = '1'
                    }
                }

                sdk.product_simulator = {};
                sdk.product_simulator.locale = '<?php echo strtolower($locale);?>',
                sdk.product_simulator.id = 'product-simulator';
                sdk.product_simulator.publicKey = '<?php echo $pagantisPublicKey;?>';
                sdk.product_simulator.selector = positionSelector;
                sdk.product_simulator.numInstalments = '<?php echo $pagantisQuotesStart;?>';
                sdk.product_simulator.type = <?php echo $pagantisSimulatorType;?>;
                sdk.product_simulator.skin = <?php echo $pagantisSimulatorSkin;?>;
                sdk.product_simulator.position = <?php echo $pagantisSimulatorPosition;?>;
                sdk.product_simulator.amountParserConfig =  {
                    thousandSeparator: '<?php echo $pagantisSimulatorThousandSeparator;?>',
                    decimalSeparator: '<?php echo $pagantisSimulatorDecimalSeparator;?>'
                };

                if (priceSelector !== 'default') {
                    sdk.product_simulator.itemAmountSelector = priceSelector;
                    if (<? echo $promoted ?> == 1) {
                        sdk.product_simulator.itemPromotedAmountSelector = priceSelector;
                    }
                }
                if (quantitySelector !== 'default' && quantitySelector !== 'none') {
                    sdk.product_simulator.itemQuantitySelector = quantitySelector;
                }
                if (price != null) {
                    sdk.product_simulator.itemAmount = price;
                    if (<? echo $promoted ?> == 1) {
                        sdk.product_simulator.itemPromotedAmount = price;
                    }
                }

                if (quantity != null) {
                    sdk.product_simulator.itemQuantity = quantity;
                }

                window.MGSimulatorId = sdk.simulator.init(sdk.product_simulator);
                return false;
            }
            return false;
        }
        if (!loadSimulator()) {
            window.loadingSimulator = setInterval(function () {
                loadSimulator();
            }, 2000);
        }
    </script>
    <div id="pagantis-simulator-product-page" class="PagantisSimulator"></div>
<?php
}
?>
