<?php
/**
 * @var int $simulatorType
 * @var bool $enabled
 * @var string $publicKey
 */
if ($pagantisIsEnabled && $pagantisSimulatorIsEnabled) {
?>
    <script>
        function loadSimulator()
        {
            if (typeof pmtSDK != 'undefined') {
                var price = null;
                var quantity = null;
                var positionSelector = '<?=$pagantisCSSSelector;?>';
                var priceSelector = '<?=$pagantisPriceSelector;?>';
                var quantitySelector = '<?=$pagantisQuantitySelector;?>';

                if (positionSelector === 'default') {
                    positionSelector = '.PagantisSimulator';
                }

                if (priceSelector === 'default') {
                    priceSelector = '[id^="product-price"]';
                    if (priceSelector === 'default') {
                        price = '<?=$amount;?>';
                    }
                }

                if (quantitySelector === 'default') {
                    quantitySelector = '.qty-wrapper #qty';
                    if (quantitySelector === 'default') {
                        quantity = '1'
                    }
                }

                pmtSDK.product_simulator = {};
                pmtSDK.product_simulator.id = 'product-simulator';
                pmtSDK.product_simulator.publicKey = '<?=$pmtPublicKey;?>';
                pmtSDK.product_simulator.selector = positionSelector;
                pmtSDK.product_simulator.numInstalments = '<?=$pmtQuotesStart;?>';
                pmtSDK.product_simulator.type = <?=$pmtSimulatorType;?>;
                pmtSDK.product_simulator.skin = <?=$pmtSimulatorSkin;?>;
                pmtSDK.product_simulator.position = <?=$pmtSimulatorPosition;?>;

                if (priceSelector !== 'default') {
                    pmtSDK.product_simulator.itemAmountSelector = priceSelector;
                }
                if (quantitySelector !== 'default' && quantitySelector !== 'none') {
                    pmtSDK.product_simulator.itemQuantitySelector = quantitySelector;
                }
                if (price != null) {
                    pmtSDK.product_simulator.itemAmount = price;
                }
                if (quantity != null) {
                    pmtSDK.product_simulator.itemQuantity = quantity;
                }

                pmtSDK.simulator.init(pmtSDK.product_simulator);
                clearInterval(window.PSSimulatorId);
            }
        }
        window.PSSimulatorId = setInterval(function () {
            loadSimulator();
        }, 2000);
    </script>
    <div id="pagantis-simulator-product-page" class="PagantisSimulator"></div>
<?php
}
?>
