<?php
/**
 * @var int $simulatorType
 * @var bool $enabled
 * @var string $publicKey
 */
if ($pagantisIsEnabled && $pagantisSimulatorIsEnabled && $pagantisPublicKey != '') {
?>
    <script>
        function findPriceSelector()
        {
            var priceDOM = document.querySelector('[id^="product-price"]');
            if (priceDOM != null ) {
                return '[id^="product-price"]';
            }
            priceDOM = document.querySelector('div.add-to-box > div.price-info > div.price-box > p.special-price');
            if (priceDOM != null ) {
                return 'div.add-to-box > div.price-info > div.price-box > p.special-price';
            }

            // Keep default for checkout price.
            return 'default';
        }

        function findQuantitySelector()
        {
            var quantityDOM = document.querySelector('.qty-wrapper #qty');
            if (quantityDOM != null) {
                return '.qty-wrapper #qty';
            }

            return 'default';
        }

        function loadSimulator()
        {
            var sdk = pgSDK;
            console.log('<?=$locale;?>');
            if ('<?=$locale;?>' == 'ES') {
                var sdk = pmtSDK;
            } else {
                var sdk = 'undefined';
            }

            var pgDiv = document.getElementsByClassName("PagantisSimulator");
            if(typeof pgDiv != 'undefined') {
                var pmtElement = pgDiv[0];
                if (pmtElement.innerHTML != '')
                {
                    clearInterval(window.MGSimulatorId);
                    return true;
                }
            }

            if (typeof sdk != 'undefined') {
                var price = null;
                var quantity = null;
                var positionSelector = '<?=$pagantisCSSSelector;?>';
                var priceSelector = '<?=$pagantisPriceSelector;?>';
                var quantitySelector = '<?=$pagantisQuantitySelector;?>';

                if (positionSelector === 'default') {
                    positionSelector = '.PagantisSimulator';
                }

                if (priceSelector === 'default') {
                    priceSelector = findPriceSelector();
                    if (priceSelector === 'default') {
                        price = '<?=$amount;?>';
                    }
                }

                if (quantitySelector === 'default') {
                    quantitySelector = findQuantitySelector();
                    if (quantitySelector === 'default') {
                        quantity = '1'
                    }
                }

                sdk.product_simulator = {};
                sdk.product_simulator.id = 'product-simulator';
                sdk.product_simulator.publicKey = '<?=$pagantisPublicKey;?>';
                sdk.product_simulator.selector = positionSelector;
                sdk.product_simulator.numInstalments = '<?=$pagantisQuotesStart;?>';
                sdk.product_simulator.type = <?=$pagantisSimulatorType;?>;
                sdk.product_simulator.skin = <?=$pagantisSimulatorSkin;?>;
                sdk.product_simulator.position = <?=$pagantisSimulatorPosition;?>;

                if (priceSelector !== 'default') {
                    sdk.product_simulator.itemAmountSelector = priceSelector;
                }
                if (quantitySelector !== 'default' && quantitySelector !== 'none') {
                    sdk.product_simulator.itemQuantitySelector = quantitySelector;
                }
                if (price != null) {
                    sdk.product_simulator.itemAmount = price;
                }
                if (quantity != null) {
                    sdk.product_simulator.itemQuantity = quantity;
                }

                sdk.simulator.init(sdk.product_simulator);
                clearInterval(window.MGSimulatorId);
            }
        }
        window.MGSimulatorId = setInterval(function () {
            loadSimulator();
        }, 2000);
    </script>
    <div id="pagantis-simulator-product-page" class="PagantisSimulator"></div>
<?php
}
?>
