version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Add Docker Host
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            echo $DOCKERHOST
            echo 127.0.0.1 magento19-test.docker | sudo tee -a /etc/hosts
      - run:
          name: Composer Install
          command: |
            sudo apt install -y software-properties-common
            sudo add-apt-repository -y ppa:ondrej/php
            sudo apt-get update
            sudo apt install -y php7.2-fpm php7.2-gd php7.2-curl php7.2-mysql php7.2-dev php7.2-cli php7.2-common php7.2-mbstring php7.2-intl php7.2-zip php7.2-bcmath php7.2-dom
            curl -s https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
            composer install --ignore-platform-reqs
      - run:
          name: Docker UP
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose up -d --build magento19-test
            docker-compose up -d --build selenium
            sleep 10
      - run:
          name: Docker Copy Module Files
          command: |
            docker cp ./extension/. magento19-test:/pagantis/
            docker exec magento19-test ls -lah /pagantis
      - run:
          name: Install Sample Data
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            docker-compose exec magento19-test install-sampledata
            docker-compose exec magento19-test install-magento
      - run:
          name: Modman, Links, N98, dev:symlinks enable
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            docker-compose exec magento19-test modman init
            docker-compose exec magento19-test modman link /pagantis
            docker-compose exec magento19-test curl -O https://files.magerun.net/n98-magerun.phar
            docker-compose exec magento19-test chmod +x n98-magerun.phar
            docker-compose exec magento19-test ./n98-magerun.phar dev:symlinks 1
      - run:
          name: magento-basic
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            extension/lib/Pagantis/bin/phpunit --group magento-basic
      - run:
          name: magento-configure-backoffice
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            extension/lib/Pagantis/bin/phpunit --group magento-configure-backoffice
      - run:
          name: magento-product-page
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            extension/lib/Pagantis/bin/phpunit --group magento-product-page
      - run:
          name: magento-buy-unregistered
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            extension/lib/Pagantis/bin/phpunit --group magento-buy-unregistered
      - run:
          name: magento-cancel-buy-unregistered
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            extension/lib/Pagantis/bin/phpunit --group magento-cancel-buy-unregistered
      - run:
          name: magento-register
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            extension/lib/Pagantis/bin/phpunit --group magento-register
      - run:
          name: magento-fill-data
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            extension/lib/Pagantis/bin/phpunit --group magento-fill-data
      - run:
          name: magento-buy-registered
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            extension/lib/Pagantis/bin/phpunit --group magento-buy-registered
      - run:
          name: magento-cancel-buy-registered
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            extension/lib/Pagantis/bin/phpunit --group magento-cancel-buy-registered
      - run:
          name: magento-controllers
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            extension/lib/Pagantis/bin/phpunit --group magento-controllers
  pushRelease:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Add Docker Host
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            echo $DOCKERHOST
            echo 127.0.0.1 magento19-test.docker | sudo tee -a /etc/hosts
      - run:
          name: Composer Install
          command: |
            sudo apt install -y software-properties-common
            sudo add-apt-repository -y ppa:ondrej/php
            sudo apt-get update
            sudo apt install -y php7.2-fpm php7.2-gd php7.2-curl php7.2-mysql php7.2-dev php7.2-cli php7.2-common php7.2-mbstring php7.2-intl php7.2-zip php7.2-bcmath php7.2-dom
            curl -s https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
            composer install
      - run:
          name: Docker UP
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose up -d --build magento19-test
            docker-compose up -d --build selenium
            sleep 10
      - run:
          name: Docker Copy Module Files
          command: |
            docker cp ./extension/. magento19-test:/pagantis/
            docker exec magento19-test ls -lah /pagantis
      - run:
          name: Install Sample Data
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            docker-compose exec magento19-test install-sampledata
            docker-compose exec magento19-test install-magento
      - run:
          name: Modman, Links, N98, dev:symlinks enable
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            docker-compose exec magento19-test modman init
            docker-compose exec magento19-test modman link /pagantis
            docker-compose exec magento19-test curl -O https://files.magerun.net/n98-magerun.phar
            docker-compose exec magento19-test chmod +x n98-magerun.phar
            docker-compose exec magento19-test ./n98-magerun.phar dev:symlinks 1
      - run:
          name: magento-basic
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            extension/lib/Pagantis/bin/phpunit --group magento-basic
      - run:
          name: Install GitHub CLI
          command: |
            curl -LO https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2
            tar xfv linux-amd64-github-release.tar.bz2
            rm linux-amd64-github-release.tar.bz2
            sudo mv bin/linux/amd64/github-release /usr/local/bin/github-release
            sudo chmod +x /usr/local/bin/github-release
      - run:
          name: Set Release Notes
          command: |
            export RELEASE_NOTES="Autogenerated package"
      - run:
          name: magento-package
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            extension/lib/Pagantis/bin/phpunit --group magento-package
            ls
      - run:
          name: Push ZIP to GitHub
          command: |
            github-release upload \
                --user pagantis \
                --repo magento-1x \
                --tag $CIRCLE_TAG \
                --name Pagantis_$CIRCLE_TAG.tgz \
                --file Pagantis_$CIRCLE_TAG.tgz
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
  release:
    jobs:
      - pushRelease:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
