version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Add Docker Host
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            echo $DOCKERHOST
            echo 127.0.0.1 magento19-test.docker | sudo tee -a /etc/hosts
      - run:
          name: Composer Install
          command: |
            sudo apt-get install python-software-properties
            sudo add-apt-repository ppa:ondrej/php
            sudo apt-get update
            sudo apt-get install -y php7.2
            curl -s https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
            composer install
      - run:
          name: Docker UP
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            docker-compose up -d --build magento-test
            docker-compose up -d --build selenium
            sleep 10
      - run:
          name: Docker Copy Module Files
          command: |
            docker cp ./extension/. magento19test:/pmt/
            docker exec magento19test ls -lah /pmt
      - run:
          name: Install Sample Data
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            docker-compose exec magento-test install-sampledata
            docker-compose exec magento-test install-magento
      - run:
          name: Modman, Links, N98, dev:symlinks enable
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            docker-compose exec magento-test modman init
            docker-compose exec magento-test modman link /pmt
            docker-compose exec magento-test curl -O https://files.magerun.net/n98-magerun.phar
            docker-compose exec magento-test chmod +x n98-magerun.phar
            docker-compose exec magento-test ./n98-magerun.phar dev:symlinks 1
      - run:
          name: Basic Test
          command: |
            export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
            extension/lib/DigitalOrigin/bin/phpunit --group magento-basic
