version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Add Docker Host
          command: echo 127.0.0.1 magento19-test.docker | sudo tee -a /etc/hosts
      - run:
          name: Composer Install
          command: composer install
      - run:
          name: Disable xdebug
          command: |
            sudo sed -i 's/^zend_extension/;zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - run:
          name: Generate
          command: ./generate.sh true
