version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Add Docker Host
          command: |
            export DOCKERHOST=$(echo $DOCKER_HOST | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
            echo $DOCKERHOST magento19-test.docker | sudo tee -a /etc/hosts
      - run:
          name: Disable xdebug
          command: |
            sudo sed -i 's/^zend_extension/;zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - run:
          name: Composer Install
          command: composer install
      - run:
          name: Docker UP
          command: |
            export DOCKERHOST=$(echo $DOCKER_HOST | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
            docker-compose up -d --build magento-test
            docker-compose up -d --build selenium
            sleep 10
      - run:
          name: Docker Copy Module Files
          command: |
            docker cp ./extension/. magento19test:/pmt/
            docker exec magento19test ls -lah /pmt
      - run:
          name: Install Sample Data
          command: |
            export DOCKERHOST=$(echo $DOCKER_HOST | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
            docker-compose exec magento-test install-sampledata
            docker-compose exec magento-test install-magento
      - run:
          name: Modman, Links, N98, dev:symlinks enable
          command: |
            export DOCKERHOST=$(echo $DOCKER_HOST | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
            docker-compose exec magento-test modman init
            docker-compose exec magento-test modman link /pmt
            docker-compose exec magento-test curl -O https://files.magerun.net/n98-magerun.phar
            docker-compose exec magento-test chmod +x n98-magerun.phar
            docker-compose exec magento-test ./n98-magerun.phar dev:symlinks 1
      - run:
          name: Basic Test
          command: |
            export DOCKERHOST=$(echo $DOCKER_HOST | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
            extension/lib/DigitalOrigin/bin/phpunit --group magento-basic
