Pepepe
<!-- Afterpay.js  -->
<script
        src="<?php echo $SDK_URL;?>"
        data-min="<?php echo $CLEARPAY_MIN_AMOUNT;?>$SDK_URL"
        data-max="<?php echo $CLEARPAY_MAX_AMOUNT;?>"
        async>
</script>
<!-- Afterpay.js -->
<div class="ClearpaySimulator">
    <style>
        afterpay-placement {
            white-space: break-spaces;
        }
    </style>
    <afterpay-placement
            data-locale="<?php echo $ISO_COUNTRY_CODE;?>"
            data-currency="<?php echo $CURRENCY;?>"
            data-amount-selector="<?php echo $PRICE_SELECTOR;?>"
            data-size="sm">
    </afterpay-placement>
</div>