<?php
/**
 * @var string $orderUrl
 * @var string $checkoutUrl
 */
?>
<script type="text/javascript">
    if (typeof pmtSDK !== 'undefined') {
        pmtSDK.modal.open("<?=$orderUrl; ?>",
            {
                id: 'iframe-pagantis',
                closeOnBackDropClick: false,
                closeOnEscPress: false,
                backDropDark: false,
                largeSize: true,
                closeConfirmationMessage: '<?=$leaveMessage;?>'
            }
        );
        pmtSDK.modal.onClose(function() {
            window.location.href = "<?=$checkoutUrl; ?>";
        });
    }
</script>