<?php
/** @var DigitalOrigin_Pmt_Block_Payment_Form $this */

$quote = $this->getQuote();
?>

<?php if ($instructions = $this->getInstructions()): ?>
    <ul class="form-list checkout-agreements" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li>
            <div class="<?php echo $this->getMethodCode() ?>-instructions-content agreement-content">
                <?php echo nl2br($instructions) ?>
            </div>
        </li>
    </ul>
<?php endif; ?>

<script>
pmt.button({
  selector: "<?php echo Mage::getStoreConfig('payment/pmt/button') ?>",
  amount: 2300,
  currency: "EUR"
});
</script>
