<?php
/**
 * @var string $orderUrl
 * @var string $checkoutUrl
 */
?>
<script type="text/javascript" src="https://cdn.pagamastarde.com/js/pmt-v2/sdk.js"></script>
<script type="text/javascript">
    if (typeof pmtClient !== 'undefined') {
        pmtClient.modal.open("<?=$orderUrl; ?>",
            {
                id: 'iframe-pagantis',
                closeOnBackDropClick: false,
                closeOnEscPress: false,
                backDropDark: false,
                largeSize: true,
                closeConfirmationMessage: '<?=$leaveMessage;?>'
            }
        );
        pmtClient.modal.onClose(function() {
            window.location.href = "<?=$checkoutUrl; ?>";
        });
    }
</script>