<?php
/**
 * @var string $orderUrl
 * @var string $checkoutUrl
 */
?>
<script type="text/javascript" src="https://cdn.pagamastarde.com/pmt-js-client-sdk/3/js/client-sdk.min.js"></script>
<script type="text/javascript">
    if (typeof pmtClient !== 'undefined') {
        pmtClient.setPublicKey('<?=$pmtPublicKey;?>');
        pmtClient.modal.open(
            "<?=$orderUrl; ?>",
            {
                closeOnBackDropClick: false,
                closeOnEscPress: false,
                backDropDark: false,
                largeSize: true,
                closeConfirmationMessage: '<?=$leaveMessage;?>'
            }
        );
        pmtClient.modal.onClose(function() {
            window.location.href = "<?=$checkoutUrl; ?>";
        });
    }
    else {
        console.log("pmtclient = UNDEFINED");
    }
</script>